# Generated by Django 2.2.2 on 2020-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('urlname', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='email',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tel', models.TextField()),
                ('part', models.TextField()),
                ('fname', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('Password', models.TextField()),
                ('ticket', models.TextField()),
                ('Mark', models.TextField()),
                ('Power', models.TextField()),
            ],
        ),
    ]
